import express from "express";
import cors from "cors";
import { prisma } from "@repo/db/client";
import { mockBankRouter } from "./mockBankCore"; //external bank simulator routes

const app = express();
app.use(express.json());
//enable CORS configuration for our frontend port
app.use(cors({
    origin: "http://localhost:3000", // allow requests only from nextjs app
    methods: ["POST", "GET", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization"]
}));

// this mounts the bank's independent endpoints onto your running instance
app.use("/api/mock-bank-core", mockBankRouter);


// can add zod validation

// the moment a user approves a deposit on the dummy bank webpage, the bank's system automatically fires a POST network request to  http://..hdfcWebhook route.

// CREDITS THE WALLET BALANCE
app.post("/hdfcWebhook", async (req, res) => {
    const paymentInformation = {
        token: req.body.token,
        userId: Number(req.body.user_identifier), // ensure it's a number to match our schema Int
        amount: Number(req.body.amount)
    };
//  here we have just used one query of updating using incremenet(a=a+amount) 
//  and not first finding the users balance in database and then update using amount=balance+newamoutbeadded
//   bcz if user double clicks then two threads would run and both first both will read current balance 100 and rhen forst thread will add money(500) and will show 600 , then second thread also add 500 but earlier had read 100 so will update to 600 only, this will be shown in database but in actual double money has been credited, 
//   database is not n sync now
//  in this apporach double money could be credited but will show correct entry in db

    try {
        // Idempotency guard: Verify we haven't already marked this transaction Success
        const existingTxn = await prisma.onRampTransaction.findUnique({
            where: { token: paymentInformation.token }
        });

        if (existingTxn?.status === "Success") {
            return res.status(200).json({ message: "Already processed successfully" });
        }
        //atomic transaction
        await prisma.$transaction([
            
            prisma.balance.update({
                where: {
                    userId: paymentInformation.userId 
                },
                data: {
                    amount: {
                        increment: paymentInformation.amount
                    }
                }
            }),
            //may be above query run but below dont bcz db goes down, so transactions

            prisma.onRampTransaction.update({
                where: {
                     //token is originally generated by your backend, passed to the frontend, sent to the bank, and finally returned via the webhook.
                    token: paymentInformation.token
                },
                data: {
                    status: "Success"
                }
            })
        ])

            
            // if anything crashes before this bracket closes, the whole block rolls back!

            // always acknowledge a webhook with a ok status so the bank stops retrying
            return res.status(200).json({ message: "Captured successfully and balance updated" });

    } catch (error) {
        console.error("HDFC_WEBHOOK_TRANSACTION_ERROR:", error);
        
        //the bank will notice the 500 and safely retry sending the webhook later
        return res.status(500).json({ message: "Failed to process webhook safely. Transaction rolled back." });
    }
}) 
app.listen(3003,()=> console.log("webhook server and bank engine running"))